const GOOGLE_SHEET_BASE_URL = process.env.GOOGLE_SHEET_BASE_URL;
const GOOGLE_SHEET_API_KEY = process.env.GOOGLE_SHEET_API_KEY;
const GOOGLE_SHEET_ID = process.env.GOOGLE_SHEET_ID;
const GOOGLE_SHEET_FABRIC_STYLE_MAPPING_RANGE = process.env.GOOGLE_SHEET_FABRIC_STYLE_MAPPING_RANGE;
const GOOGLE_SHEET_FABRIC_AVERAGE_RANGE = process.env.GOOGLE_SHEET_FABRIC_AVERAGE_RANGE;
const GOOGLE_SHEET_STYLE_AVERAGE_RANGE = process.env.GOOGLE_SHEET_STYLE_AVERAGE_RANGE;
module.exports = {
  GOOGLE_SHEET_BASE_URL,
  GOOGLE_SHEET_API_KEY,
  GOOGLE_SHEET_ID,
  GOOGLE_SHEET_FABRIC_STYLE_MAPPING_RANGE,
  GOOGLE_SHEET_FABRIC_AVERAGE_RANGE,
  GOOGLE_SHEET_STYLE_AVERAGE_RANGE,
};
